/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hs.personnel;

import com.hs.personnel.dao.ClockOnDao;
import com.hs.personnel.dao.EmployeeDao;
import java.awt.image.BufferedImage;
import java.util.List;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import utils.ImageUtil;

/**
 *
 * @author vincenttuan
 */
public class ReportJFrame extends javax.swing.JFrame {

    private EmployeeDao employeeDao = new EmployeeDao();

    private ClockOnDao clockOnDao = new ClockOnDao();

    public ReportJFrame() {
        initComponents();
        listEmployees();
        // 調整欄位高度/寬度
        jtable_emp.setRowHeight(30);
        jtable_clockon.setRowHeight(30);
        jtable_clockon.getColumnModel().getColumn(3).setPreferredWidth(250);
        
    }

    private void listEmployees() {
        DefaultTableModel dm = (DefaultTableModel) jtable_emp.getModel();
        dm.setRowCount(0);
        List<Map<String, Object>> list = employeeDao.queryAll();

        for (Map<String, Object> map : list) {
            Object[] rowData = {
                map.get("emp_no"),
                map.get("emp_name")
            };
            dm.addRow(rowData);
        }
    }

    private void listClockOn(String emp_no, String begin, String end) {
        DefaultTableModel dm = (DefaultTableModel) jtable_clockon.getModel();
        dm.setRowCount(0); // 清空 jTable
        List<Map<String, String>> list = clockOnDao.query(emp_no, begin, end);
        for (Map<String, String> map : list) {
            Object[] rowData = {
                map.get("clock_id"),
                map.get("emp_no"),
                map.get("emp_name"),
                map.get("status_name"),
                map.get("clock_on")
            };
            dm.addRow(rowData);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        edit_begin = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        edit_end = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtable_emp = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtable_clockon = new javax.swing.JTable();
        image1 = new javax.swing.JLabel();
        image2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("打卡資料查詢");

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setText("日期區間");

        edit_begin.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        edit_begin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        edit_begin.setText("2019-8-1");
        edit_begin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_beginActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel2.setText("~");

        edit_end.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        edit_end.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        edit_end.setText("2019-9-30");
        edit_end.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_endActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jButton1.setText("查詢");

        jButton2.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jButton2.setText("匯出");

        jtable_emp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "emp_no", "emp_name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtable_emp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtable_empMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtable_emp);

        jtable_clockon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "emp_id", "emp_no", "emp_name", "status_name", "clock_on"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtable_clockon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtable_clockonMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtable_clockon);

        image1.setText("image1 沒有照片");

        image2.setText("image2 沒有照片");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(image1, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
                            .addComponent(image2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(edit_begin, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(edit_end, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(edit_begin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(edit_end, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(image1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(image2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void edit_beginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_beginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edit_beginActionPerformed

    private void edit_endActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_endActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edit_endActionPerformed

    private void jtable_empMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtable_empMouseClicked

        DefaultTableModel dm = (DefaultTableModel) jtable_emp.getModel();
        int row = jtable_emp.getSelectedRow();
        int col = 0;
        String emp_no = dm.getValueAt(row, col).toString();
        String begin = edit_begin.getText();
        String end = edit_end.getText();

        listClockOn(emp_no, begin, end);
        
        // 取得員工實體照片
        image1.setIcon(new ImageIcon("/Users/vincenttuan/NetBeansProjects/HS_Personnel/photo/" + emp_no + ".png"));
        if(image1.getIcon().getIconHeight() == -1) {
            image1.setText("image1 沒有照片");
        } else {
            image1.setText("");
        }
        image2.setIcon(null);
        image2.setText("image2 沒有照片");
    }//GEN-LAST:event_jtable_empMouseClicked

    private void jtable_clockonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtable_clockonMouseClicked
        DefaultTableModel dm = (DefaultTableModel) jtable_clockon.getModel();
        int row = jtable_clockon.getSelectedRow();
        int col = 0;
        // 取得所選取到的 clock_id
        int clock_id = Integer.parseInt(dm.getValueAt(row, col).toString());
        // 取得 image 字串 (base64)
        String imageBase64 = clockOnDao.getImage(clock_id);
        if(imageBase64 == null) {
            image2.setIcon(null);
            image2.setText("image2 沒有照片");
        } else {
            // 字串(base64) 轉 bufferedImage
            BufferedImage bufferedImage = ImageUtil.base64StringToImage(imageBase64);
            // bufferedImage 轉 ImageIcon 並送入 image2 中來顯示 
            image2.setIcon(new ImageIcon(bufferedImage));
            image2.setText("");
        }
        
    }//GEN-LAST:event_jtable_clockonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReportJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReportJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReportJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReportJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReportJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField edit_begin;
    private javax.swing.JTextField edit_end;
    private javax.swing.JLabel image1;
    private javax.swing.JLabel image2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jtable_clockon;
    private javax.swing.JTable jtable_emp;
    // End of variables declaration//GEN-END:variables
}
